apiVersion: v1
kind: Service
metadata:
  name: bridge-forky-transfer-svc
  namespace: transfer
spec:
  selector:
    app: bridge-forky-transfer
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP